In [376]:
import pandas as pd
import numpy as np

In [377]:
df_train = pd.read_csv("train.csv")
df_train.head()

,id,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
0,0,Ford,F-150 Lariat,2018,74349,Gasoline,375.0HP 3.5L V6 Cylinder Engine Gasoline Fuel,10-Speed A/T,Blue,Gray,None reported,Yes,11000
1,1,BMW,335 i,2007,80000,Gasoline,300.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,6-Speed M/T,Black,Black,None reported,Yes,8250
2,2,Jaguar,XF Luxury,2009,91491,Gasoline,300.0HP 4.2L 8 Cylinder Engine Gasoline Fuel,6-Speed A/T,Purple,Beige,None reported,Yes,15000
3,3,BMW,X7 xDrive40i,2022,2437,Hybrid,335.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,Transmission w/Dual Shift Mode,Gray,Brown,None reported,Yes,63500
4,4,Pontiac,Firebird Base,2001,111000,Gasoline,200.0HP 3.8L V6 Cylinder Engine Gasoline Fuel,A/T,White,Black,None reported,Yes,7850

In [378]:
df_test = pd.read_csv("test.csv")
df_test.head()

,id,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title
0,54273,Mercedes-Benz,E-Class E 350,2014,73000,Gasoline,302.0HP 3.5L V6 Cylinder Engine Gasoline Fuel,A/T,White,Beige,None reported,Yes
1,54274,Lexus,RX 350 Base,2015,128032,Gasoline,275.0HP 3.5L V6 Cylinder Engine Gasoline Fuel,8-Speed A/T,Silver,Black,None reported,Yes
2,54275,Mercedes-Benz,C-Class C 300,2015,51983,Gasoline,241.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,7-Speed A/T,Blue,White,None reported,Yes
3,54276,Land,Rover Range Rover 5.0L Supercharged Autobiogra...,2018,29500,Gasoline,518.0HP 5.0L 8 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,White,White,At least 1 accident or damage reported,Yes
4,54277,BMW,X6 xDrive40i,2020,90000,Gasoline,335.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,8-Speed A/T,White,Black,At least 1 accident or damage reported,Yes

In [379]:
df_train['price'].mean()

39218.443332780575

In [380]:
df_train.isnull().sum()

id              0
brand           0
model           0
model_year      0
milage          0
fuel_type       0
engine          0
transmission    0
ext_col         0
int_col         0
accident        0
clean_title     0
price           0
dtype: int64

In [381]:
df_train.describe()

                 id    model_year         milage         price
count  54273.000000  54273.000000   54273.000000  5.427300e+04
mean   27136.000000   2015.091979   72746.175667  3.921844e+04
std    15667.409917      5.588909   50469.490448  7.282634e+04
min        0.000000   1974.000000     100.000000  2.000000e+03
25%    13568.000000   2012.000000   32268.000000  1.550000e+04
50%    27136.000000   2016.000000   66107.000000  2.800000e+04
75%    40704.000000   2019.000000  102000.000000  4.500000e+04
max    54272.000000   2024.000000  405000.000000  2.954083e+06

In [382]:
df_train.columns

Index(['id', 'brand', 'model', 'model_year', 'milage', 'fuel_type', 'engine',
       'transmission', 'ext_col', 'int_col', 'accident', 'clean_title',
       'price'],
      dtype='object')

In [383]:
#df_test['price'] = pd.Series([df_train['price'].mean() * len(df_train))

In [384]:
df_test

,id,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title
0,54273,Mercedes-Benz,E-Class E 350,2014,73000,Gasoline,302.0HP 3.5L V6 Cylinder Engine Gasoline Fuel,A/T,White,Beige,None reported,Yes
1,54274,Lexus,RX 350 Base,2015,128032,Gasoline,275.0HP 3.5L V6 Cylinder Engine Gasoline Fuel,8-Speed A/T,Silver,Black,None reported,Yes
2,54275,Mercedes-Benz,C-Class C 300,2015,51983,Gasoline,241.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,7-Speed A/T,Blue,White,None reported,Yes
3,54276,Land,Rover Range Rover 5.0L Supercharged Autobiogra...,2018,29500,Gasoline,518.0HP 5.0L 8 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,White,White,At least 1 accident or damage reported,Yes
4,54277,BMW,X6 xDrive40i,2020,90000,Gasoline,335.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,8-Speed A/T,White,Black,At least 1 accident or damage reported,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...
36178,90451,GMC,Yukon Denali,2019,4500,Gasoline,420.0HP 6.2L 8 Cylinder Engine Gasoline Fuel,10-Speed A/T,Gray,Black,None reported,Yes
36179,90452,Chevrolet,Silverado 1500 Z71 Extended Cab,2004,185000,Gasoline,295.0HP 5.3L 8 Cylinder Engine Gasoline Fuel,4-Speed A/T,Red,Gray,At least 1 accident or damage reported,Yes
36180,90453,Toyota,Corolla LE,2011,116000,Gasoline,132.0HP 1.8L 4 Cylinder Engine Gasoline Fuel,5-Speed M/T,Beige,Gray,None reported,Yes
36181,90454,Lincoln,Navigator Reserve,2019,39000,Gasoline,450.0HP 3.5L V6 Cylinder Engine Gasoline Fuel,10-Speed A/T,Black,Orange,None reported,Yes
36182,90455,Chevrolet,Tahoe LT,2012,162731,E85 Flex Fuel,320.0HP 5.3L 8 Cylinder Engine Flex Fuel Capab...,A/T,Black,Black,At least 1 accident or damage reported,Yes

In [385]:
#df_test[['id','price']].to_csv('submission.csv',index=False)

In [386]:
df_train['brand'].unique()

array(['Ford', 'BMW', 'Jaguar', 'Pontiac', 'Acura', 'Audi', 'GMC',
       'Maserati', 'Chevrolet', 'Porsche', 'Mercedes-Benz', 'Tesla',
       'Lexus', 'Kia', 'Lincoln', 'Dodge', 'Volkswagen', 'Land',
       'Cadillac', 'Mazda', 'RAM', 'Subaru', 'Hyundai', 'MINI', 'Jeep',
       'Honda', 'Hummer', 'Nissan', 'Toyota', 'Volvo', 'Genesis',
       'Mitsubishi', 'Buick', 'INFINITI', 'McLaren', 'Scion',
       'Lamborghini', 'Bentley', 'Suzuki', 'Ferrari', 'Alfa',
       'Rolls-Royce', 'Chrysler', 'Aston', 'Rivian', 'Lotus', 'Saturn',
       'Lucid', 'Mercury', 'Maybach', 'FIAT', 'Plymouth', 'Bugatti'],
      dtype=object)

In [387]:
print(df_train['brand'].value_counts()['Ford'],df_train['brand'].value_counts()['BMW'],df_train['brand'].value_counts()['Scion'])

6706 7369 53

In [388]:
len(df_train['model'].unique())

1827

In [389]:
df_train['model_year'].unique()

array([2018, 2007, 2009, 2022, 2001, 2003, 2014, 2019, 2016, 2017, 2013,
       2021, 2015, 2020, 2012, 2006, 2023, 2011, 2010, 1999, 2004, 1993,
       2002, 2005, 2008, 1995, 1998, 2000, 1997, 1994, 1996, 2024, 1992,
       1974], dtype=int64)

In [390]:
len(df_train['fuel_type'].unique())

7

In [391]:
df_train['transmission'].unique()

array(['10-Speed A/T', '6-Speed M/T', '6-Speed A/T',
       'Transmission w/Dual Shift Mode', 'A/T', '5-Speed M/T',
       '7-Speed A/T', '5-Speed A/T', '8-Speed A/T',
       'Transmission Overdrive Switch', '9-Speed Automatic',
       '7-Speed M/T', '10-Speed Automatic', '6-Speed Automatic', 'M/T',
       '5-Speed Automatic', 'CVT Transmission', '9-Speed A/T',
       '8-Speed Automatic', '4-Speed A/T', 'Automatic', '1-Speed A/T',
       '8-Speed Automatic with Auto-Shift', '7-Speed DCT Automatic',
       'Automatic CVT', '7-Speed Automatic',
       '7-Speed Automatic with Auto-Shift', '4-Speed Automatic',
       '6-Speed Automatic with Auto-Shift', '6-Speed Manual',
       '7-Speed Manual',
       '6-Speed Electronically Controlled Automatic with O',
       '1-Speed Automatic', '10-Speed Automatic with Overdrive',
       '8-Speed Manual', '2-Speed A/T', 'CVT-F', '–', 'F',
       '9-Speed Automatic with Auto-Shift', '7-Speed', 'Variable',
       'SCHEDULED FOR OR IN PRODUCTION', '6-Speed', '6 Speed At/Mt',
       '6 Speed Mt'], dtype=object)

In [392]:
len(df_train['engine'].unique())

1061

In [393]:
df_train['ext_col'].unique(), len(df_train['ext_col'].unique())

(array(['Blue', 'Black', 'Purple', 'Gray', 'White', 'Red', 'Silver',
        'Summit White', 'Platinum Quartz Metallic', 'Green', 'Orange',
        'Lunar Rock', 'Red Quartz Tintcoat', 'Beige', 'Gold',
        'Jet Black Mica', 'Delmonico Red Pearlcoat', 'Brown',
        'Rich Garnet Metallic', 'Stellar Black Metallic', 'Yellow',
        'Deep Black Pearl Effect', 'Metallic', 'Ice Silver Metallic',
        'Agate Black Metallic', 'Rosso Mars Metallic', 'White Clearcoat',
        'Santorini Black Metallic', 'DB Black Clearcoat',
        'Snowflake White Pearl', 'Glacial White Pearl',
        'Maximum Steel Metallic', 'Blue Caelum', 'Dark Matter Metallic',
        '–', 'Oxford White', 'Cobra Beige Metallic',
        'Velvet Red Pearlcoat', 'Python Green', 'Obsidian Black Metallic',
        'Beluga Black', 'Blue Reflex Mica', 'Sparkling Silver',
        'Black Clearcoat', 'Soul Red Crystal Metallic',
        'Bright White Clearcoat', 'Shimmering Silver',
        'Midnight Black Metallic', 'Cajun Red Tintcoat',
        'Cirrus Silver Metallic', 'Blu', 'Burnished Bronze Metallic',
        'Hellayella Clearcoat', 'Diamond Black', 'White Diamond Tri-Coat',
        'Nebula Gray Pearl', 'Bronze Dune Metallic',
        'Polymetal Gray Metallic', 'Nightfall Gray Metallic', 'Fuji White',
        'Shadow Gray Metallic', 'Dark Moon Blue Metallic', 'Dark Sapphire',
        'Firecracker Red Clearcoat', 'Black Raven',
        'White Knuckle Clearcoat', 'Siren Red Tintcoat',
        'Designo Magno Matte', 'Atomic Silver',
        'Billet Silver Metallic Clearcoat', 'Ember Pearlcoat',
        'Magnetic Black', 'Pacific Blue Metallic',
        'Midnight Blue Metallic', 'Alta White', 'Eiger Grey',
        'Diamond White', 'Onyx', 'Hyper Red', 'Ebony Twilight Metallic',
        'Alpine White', 'Sonic Silver Metallic', 'Dark Ash Metallic',
        'Volcano Grey Metallic', 'Patriot Blue Pearlcoat', 'Onyx Black',
        'Titanium Silver', 'Granite Crystal Clearcoat Metallic',
        'Nero Noctis', 'Silver Zynith', 'Black Cherry',
        'Iconic Silver Metallic', 'Nero Daytona',
        'Daytona Gray Pearl Effect', 'Dark Moss', 'Deep Crystal Blue Mica',
        'China Blue', 'Magnetic Metallic', 'Midnight Black', 'Vega Blue',
        'Sandstone Metallic', 'Machine Gray Metallic', 'C / C',
        'Platinum Gray Metallic', 'Silver Ice Metallic',
        'Carrara White Metallic', 'Black Sapphire Metallic', 'Go Mango!',
        'White Frost Tri-Coat', 'Lizard Green', 'Santorin Black',
        'Twilight Black', 'Gecko Pearlcoat', 'Satin Steel Metallic',
        'Imperial Blue Metallic', 'Nautical Blue Pearl',
        'Stone Gray Metallic', 'Quartzite Grey Metallic',
        'Majestic Black Pearl', 'Shadow Black', 'Crimson Red Tintcoat',
        'Silver Flare Metallic', 'Vik Black', 'Lunar Silver Metallic',
        'Maroon', 'Redline Red', 'Iridescent Pearl Tricoat',
        'Brilliant Silver Metallic', 'Lunar Blue Metallic', 'Matte White',
        'Tan', 'Stormy Sea', 'Twilight Blue Metallic', 'Ibis White',
        'Kodiak Brown Metallic', 'Crystal Black Silica',
        'Sting Gray Clearcoat', 'Pristine White', 'Pearl White',
        'Antimatter Blue Metallic', 'Tango Red Metallic',
        'Crystal Black Pearl', 'Rift Metallic', 'Glacier White Metallic',
        'Quartz White', 'Black Obsidian', 'Brilliant Black',
        'Ruby Red Metallic Tinted Clearcoat', 'Tungsten Metallic',
        'Magnetite Black Metallic', 'Jupiter Red', 'Glacier',
        'Santorini Black', 'Navarre Blue',
        'Phantom Black Pearl Effect / Black Roof',
        'Isle of Man Green Metallic', 'Snowflake White Pearl Metallic',
        'Brands Hatch Gray Metallic', 'Volcanic Orange', 'Liquid Platinum',
        'Bayside Blue', 'Rapid Red Metallic Tinted Clearcoat',
        'Majestic Plum Metallic', 'White Platinum Tri-Coat Metallic',
        'Mosaic Black Metallic', 'Chalk', 'Black Noir Pearl',
        'Nightfall Mica', 'Dark Gray Metallic', 'Mythos Black Metallic',
        'Blueprint', 'Quicksilver Metallic', 'Frozen White',
        'Lunare White Metallic', 'Verde', 'Dark Graphite Metallic',
        'Mythos Black', 'Ebony Black', 'Ultra Black',
        'Ingot Silver Metallic', 'Glacier Silver Metallic', 'Gun Metallic',
        'Wind Chill Pearl', 'Anodized Blue Metallic',
        'designo Diamond White', 'Tempest', 'Caviar',
        'Phytonic Blue Metallic', 'Moonlight Cloud',
        'Daytona Gray Pearl Effect w/ Black Roof', 'Bianco Isis',
        'Carbonized Gray Metallic', 'Deep Blue Metallic',
        'Ametrin Metallic', 'Super Black', 'Rosso Corsa', 'Blue Metallic',
        'Iridium Metallic', 'Dark Slate Metallic',
        'Manhattan Noir Metallic', 'Alfa White', 'Baltic Gray',
        'Northsky Blue Metallic', 'Super White', 'Carbon Black Metallic',
        'Horizon Blue', 'Jungle Green', 'Cayenne Red Tintcoat', 'Pink',
        'Daytona Gray', 'Gentian Blue Metallic', 'Sangria Red',
        'Kemora Gray Metallic', 'Magnetite Gray Metallic',
        'Octane Red Pearlcoat', 'Custom Color', 'Ultra White',
        'Pacific Blue', 'Ruby Flare Pearl', 'Caspian Blue',
        'Silver Radiance', 'Carpathian Grey Premium Metallic', 'Ice',
        'Balloon White', 'Shoreline Blue Pearl', 'Firenze Red Metallic',
        'Remington Red Metallic', 'Orca Black Metallic',
        'Radiant Red Metallic II', 'Mineral White', 'Glacier White',
        'Snow White Pearl', 'Iridium Silver Metallic', 'Carpathian Grey',
        'Mountain Air Metallic', 'Selenite Gray Metallic',
        'Graphite Grey Metallic', 'Selenite Grey Metallic', 'Kinetic Blue',
        'Wolf Gray', 'Star White', 'Emin White', 'Indus Silver',
        'Matador Red Metallic', 'Portofino Gray', 'Black Forest Green',
        'Dazzling White', 'Flame Red Clearcoat', 'Glacier Blue Metallic',
        'Arctic White', 'Rosso', 'Silver Mist', 'Bianco Icarus Metallic',
        'Firenze Red', 'Ironman Silver', 'Red Obsession',
        'Magnetic Gray Metallic', 'Garnet Red Metallic',
        'Vulcano Black Metallic', 'Magnetic Gray Clearcoat'], dtype=object),
 260)

In [394]:
df_train['int_col'].unique(), len(df_train['int_col'].unique())

(array(['Gray', 'Black', 'Beige', 'Brown', 'Silver', 'Jet Black', 'Mesa',
        'White', '–', 'Red', 'Blue', 'Medium Stone', 'Ash', 'Ebony',
        'Shara Beige', 'Tan', 'Titan Black / Quarzit', 'Global Black',
        'Orange', 'Saddle Brown', 'Nero Ade', 'Beluga', 'Light Slate',
        'Gold', 'Black Onyx', 'Nougat Brown', 'Camel', 'Hotspur Hide',
        'Charcoal', 'Satin Black', 'Deep Chestnut', 'Diesel Gray / Black',
        'White / Brown', 'AMG Black', 'Parchment', 'Shale',
        'Canberra Beige', 'Sahara Tan', 'Ebony / Pimento', 'Rhapsody Blue',
        'Medium Dark Slate', 'Rioja Red', 'Black / Express Red',
        'Deep Garnet', 'Portland', 'Sandstone', 'Dark Ash', 'Deep Cypress',
        'Black / Stone Grey', 'Chestnut', 'Navy Pier', 'Green',
        'Giallo Taurus / Nero Ade', 'Mistral Gray / Raven', 'Dark Gray',
        'Amber', 'Charles Blue', 'Hotspur', 'Medium Earth Gray', 'Ceramic',
        'Kyalami Orange', 'Charcoal Black', 'Adrenaline Red', 'Walnut',
        'Brandy', 'Black / Saddle', 'Obsidian Black', 'Oyster W/Contrast',
        'Macchiato', 'Red / Black', 'Whisper Beige', 'Graphite', 'Yellow',
        'Medium Light Camel', 'Slate', 'Nero', 'Ebony Black', 'Espresso',
        'Cappuccino', 'Ivory / Ebony', 'Boulder', 'Medium Ash Gray',
        'Platinum', 'Light Platinum / Jet Black', 'Beluga Hide',
        'Black / Graphite', 'Canberra Beige/Black', 'Rock Gray',
        'Dark Auburn', 'Almond Beige', 'Sand Beige', 'Black / Brown',
        'Ice', 'Silk Beige/Espresso Brown', 'Dark Galvanized',
        'Cobalt Blue', 'Grace White', 'Titan Black', 'Cocoa / Dune',
        'Light Gray', 'Camel Leather', 'Light Titanium',
        'Pimento Red w/Ebony', 'Sport', 'Oyster/Black', 'Black/Red',
        'Ebony / Ebony Accents', 'Cloud', 'Graystone', 'BLACK',
        'Mountain Brown', 'Linen', 'Caramel', 'Black / Gray', 'Blk',
        'Black w/Red Stitching', 'Mocha', 'Tupelo', 'Tan/Ebony',
        'Parchment.', 'Black/Gun Metal', 'Very Light Cashmere',
        'Medium Pewter', 'Red/Black'], dtype=object),
 124)

In [395]:
df_train['accident'].unique()

array(['None reported', 'At least 1 accident or damage reported'],
      dtype=object)

In [396]:
len(df_train['clean_title'])

54273

In [397]:
df_train

,id,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
0,0,Ford,F-150 Lariat,2018,74349,Gasoline,375.0HP 3.5L V6 Cylinder Engine Gasoline Fuel,10-Speed A/T,Blue,Gray,None reported,Yes,11000
1,1,BMW,335 i,2007,80000,Gasoline,300.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,6-Speed M/T,Black,Black,None reported,Yes,8250
2,2,Jaguar,XF Luxury,2009,91491,Gasoline,300.0HP 4.2L 8 Cylinder Engine Gasoline Fuel,6-Speed A/T,Purple,Beige,None reported,Yes,15000
3,3,BMW,X7 xDrive40i,2022,2437,Hybrid,335.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,Transmission w/Dual Shift Mode,Gray,Brown,None reported,Yes,63500
4,4,Pontiac,Firebird Base,2001,111000,Gasoline,200.0HP 3.8L V6 Cylinder Engine Gasoline Fuel,A/T,White,Black,None reported,Yes,7850
...,...,...,...,...,...,...,...,...,...,...,...,...,...
54268,54268,BMW,X6 xDrive50i,2017,29000,Gasoline,445.0HP 4.4L 8 Cylinder Engine Gasoline Fuel,8-Speed A/T,White,Brown,None reported,Yes,29000
54269,54269,Audi,A4 2.0T Premium,2015,94634,E85 Flex Fuel,220.0HP 2.0L 4 Cylinder Engine Flex Fuel Capab...,6-Speed A/T,Black,Black,At least 1 accident or damage reported,Yes,6500
54270,54270,Porsche,Cayenne S,2013,40989,Gasoline,420.0HP 3.6L V6 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,White,Black,At least 1 accident or damage reported,Yes,18950
54271,54271,Porsche,911 Carrera 4 GTS,2023,1518,Gasoline,4.0L H6 24V GDI DOHC,8-Speed Automatic with Auto-Shift,Beige,Brown,None reported,Yes,194965
54272,54272,Audi,A5 Sportback S line Premium Plus,2021,35000,Hybrid,261.0HP 2.0L 4 Cylinder Engine Gasoline/Mild E...,8-Speed A/T,Black,Black,None reported,Yes,37499

In [398]:
from sklearn.preprocessing import LabelEncoder

In [399]:
#label_encoder = LabelEncoder()

# Apply LabelEncoder to the 'color' column
#df_train['brand_encoded'] = label_encoder.fit_transform(df_train['brand'])
#df_train['model_year_encoded'] = label_encoder.fit_transform(df_train['model_year'])
#df_train['accident_encoded'] = label_encoder.fit_transform(df_train['accident'])
#df_train['fuel_type_encoded'] = label_encoder.fit_transform(df_train['fuel_type'])

In [400]:
df_train = pd.get_dummies(df_train, columns=['brand','model_year','accident','fuel_type'], dtype= np.uint8)

In [401]:
df_train.columns

Index(['id', 'model', 'milage', 'engine', 'transmission', 'ext_col', 'int_col',
       'clean_title', 'price', 'brand_Acura',
       ...
       'model_year_2024', 'accident_At least 1 accident or damage reported',
       'accident_None reported', 'fuel_type_Diesel', 'fuel_type_E85 Flex Fuel',
       'fuel_type_Gasoline', 'fuel_type_Hybrid', 'fuel_type_Plug-In Hybrid',
       'fuel_type_not supported', 'fuel_type_–'],
      dtype='object', length=105)

In [402]:
df_train.head()

,id,model,milage,engine,transmission,ext_col,int_col,clean_title,price,brand_Acura,...,model_year_2024,accident_At least 1 accident or damage reported,accident_None reported,fuel_type_Diesel,fuel_type_E85 Flex Fuel,fuel_type_Gasoline,fuel_type_Hybrid,fuel_type_Plug-In Hybrid,fuel_type_not supported,fuel_type_–
0,0,F-150 Lariat,74349,375.0HP 3.5L V6 Cylinder Engine Gasoline Fuel,10-Speed A/T,Blue,Gray,Yes,11000,0,...,0,0,1,0,0,1,0,0,0,0
1,1,335 i,80000,300.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,6-Speed M/T,Black,Black,Yes,8250,0,...,0,0,1,0,0,1,0,0,0,0
2,2,XF Luxury,91491,300.0HP 4.2L 8 Cylinder Engine Gasoline Fuel,6-Speed A/T,Purple,Beige,Yes,15000,0,...,0,0,1,0,0,1,0,0,0,0
3,3,X7 xDrive40i,2437,335.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,Transmission w/Dual Shift Mode,Gray,Brown,Yes,63500,0,...,0,0,1,0,0,0,1,0,0,0
4,4,Firebird Base,111000,200.0HP 3.8L V6 Cylinder Engine Gasoline Fuel,A/T,White,Black,Yes,7850,0,...,0,0,1,0,0,1,0,0,0,0

In [403]:
column_to_move = 'price'

# Pop the column and store it
column = df_train.pop(column_to_move)

# Insert the column at the end
df_train[column_to_move] = column

In [404]:
df_train.head()

,id,model,milage,engine,transmission,ext_col,int_col,clean_title,brand_Acura,brand_Alfa,...,accident_At least 1 accident or damage reported,accident_None reported,fuel_type_Diesel,fuel_type_E85 Flex Fuel,fuel_type_Gasoline,fuel_type_Hybrid,fuel_type_Plug-In Hybrid,fuel_type_not supported,fuel_type_–,price
0,0,F-150 Lariat,74349,375.0HP 3.5L V6 Cylinder Engine Gasoline Fuel,10-Speed A/T,Blue,Gray,Yes,0,0,...,0,1,0,0,1,0,0,0,0,11000
1,1,335 i,80000,300.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,6-Speed M/T,Black,Black,Yes,0,0,...,0,1,0,0,1,0,0,0,0,8250
2,2,XF Luxury,91491,300.0HP 4.2L 8 Cylinder Engine Gasoline Fuel,6-Speed A/T,Purple,Beige,Yes,0,0,...,0,1,0,0,1,0,0,0,0,15000
3,3,X7 xDrive40i,2437,335.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,Transmission w/Dual Shift Mode,Gray,Brown,Yes,0,0,...,0,1,0,0,0,1,0,0,0,63500
4,4,Firebird Base,111000,200.0HP 3.8L V6 Cylinder Engine Gasoline Fuel,A/T,White,Black,Yes,0,0,...,0,1,0,0,1,0,0,0,0,7850

In [405]:
df_train_sub = df_train.drop(columns=['id', 'model', 'engine',
       'transmission', 'ext_col', 'int_col', 'clean_title',
       ], inplace=False)

In [406]:
df_train_sub.head()

,milage,brand_Acura,brand_Alfa,brand_Aston,brand_Audi,brand_BMW,brand_Bentley,brand_Bugatti,brand_Buick,brand_Cadillac,...,accident_At least 1 accident or damage reported,accident_None reported,fuel_type_Diesel,fuel_type_E85 Flex Fuel,fuel_type_Gasoline,fuel_type_Hybrid,fuel_type_Plug-In Hybrid,fuel_type_not supported,fuel_type_–,price
0,74349,0,0,0,0,0,0,0,0,0,...,0,1,0,0,1,0,0,0,0,11000
1,80000,0,0,0,0,1,0,0,0,0,...,0,1,0,0,1,0,0,0,0,8250
2,91491,0,0,0,0,0,0,0,0,0,...,0,1,0,0,1,0,0,0,0,15000
3,2437,0,0,0,0,1,0,0,0,0,...,0,1,0,0,0,1,0,0,0,63500
4,111000,0,0,0,0,0,0,0,0,0,...,0,1,0,0,1,0,0,0,0,7850

In [407]:
from sklearn.preprocessing import StandardScaler
column_to_scale = 'milage'

# Initialize the StandardScaler
scaler = StandardScaler()

# Fit and transform the selected column
df_train_sub[column_to_scale] = scaler.fit_transform(df_train_sub[[column_to_scale]])

In [444]:
df_train_sub.head()

,milage,brand_Acura,brand_Alfa,brand_Aston,brand_Audi,brand_BMW,brand_Bentley,brand_Bugatti,brand_Buick,brand_Cadillac,...,fuel_type_Diesel,fuel_type_E85 Flex Fuel,fuel_type_Gasoline,fuel_type_Hybrid,fuel_type_Plug-In Hybrid,fuel_type_not supported,fuel_type_–,price,linear_predictions,polynomial_prediction
0,0.031759,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,11000,37536.0,37178.0
1,0.143728,0,0,0,0,1,0,0,0,0,...,0,0,1,0,0,0,0,8250,26488.0,25114.0
2,0.371412,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,15000,26056.0,21230.0
3,-1.393115,0,0,0,0,1,0,0,0,0,...,0,0,0,1,0,0,0,63500,68096.0,75454.0
4,0.757966,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,7850,9576.0,19806.0

In [409]:
X_train = df_train_sub.to_numpy()[:,:-1]
X_train

array([[ 0.03175858,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.14372824,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.37141245,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [-0.62924091,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [-1.41132457,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [-0.74790776,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ]])

In [410]:
y_train = df_train_sub.to_numpy()[:,-1]
y_train

array([ 11000.,   8250.,  15000., ...,  18950., 194965.,  37499.])

In [411]:
from sklearn.linear_model import LinearRegression
model = LinearRegression().fit(X_train, y_train)

In [412]:
model.coef_

array([-8.27843747e+03,  3.75112541e+16,  3.75112541e+16,  3.75112541e+16,
        3.75112541e+16,  3.75112541e+16,  3.75112541e+16,  3.75112541e+16,
        3.75112541e+16,  3.75112541e+16,  3.75112541e+16,  3.75112541e+16,
        3.75112541e+16,  3.75112541e+16,  3.75112541e+16,  3.75112541e+16,
        3.75112541e+16,  3.75112541e+16,  3.75112541e+16,  3.75112541e+16,
        3.75112541e+16,  3.75112541e+16,  3.75112541e+16,  3.75112541e+16,
        3.75112541e+16,  3.75112541e+16,  3.75112541e+16,  3.75112541e+16,
        3.75112541e+16,  3.75112541e+16,  3.75112541e+16,  3.75112541e+16,
        3.75112541e+16,  3.75112541e+16,  3.75112541e+16,  3.75112541e+16,
        3.75112541e+16,  3.75112541e+16,  3.75112541e+16,  3.75112541e+16,
        3.75112541e+16,  3.75112541e+16,  3.75112541e+16,  3.75112541e+16,
        3.75112541e+16,  3.75112541e+16,  3.75112541e+16,  3.75112541e+16,
        3.75112541e+16,  3.75112541e+16,  3.75112541e+16,  3.75112541e+16,
        3.75112541e+16,  3.75112541e+16,  2.12978248e+16,  2.12978248e+16,
        2.12978248e+16,  2.12978248e+16,  2.12978248e+16,  2.12978248e+16,
        2.12978248e+16,  2.12978248e+16,  2.12978248e+16,  2.12978248e+16,
        2.12978248e+16,  2.12978248e+16,  2.12978248e+16,  2.12978248e+16,
        2.12978248e+16,  2.12978248e+16,  2.12978248e+16,  2.12978248e+16,
        2.12978248e+16,  2.12978248e+16,  2.12978248e+16,  2.12978248e+16,
        2.12978248e+16,  2.12978248e+16,  2.12978248e+16,  2.12978248e+16,
        2.12978248e+16,  2.12978248e+16,  2.12978248e+16,  2.12978248e+16,
        2.12978248e+16,  2.12978248e+16,  2.12978248e+16,  2.12978248e+16,
       -1.04226818e+17, -1.04226818e+17,  9.71913025e+16,  9.71913025e+16,
        9.71913025e+16,  9.71913025e+16,  9.71913025e+16,  9.71913025e+16,
        9.71913025e+16])

In [413]:
model.intercept_

-5.1773563193856456e+16

In [414]:
df_train_sub['linear_predictions'] = model.predict(X_train)

In [415]:
df_train_sub.head()

,milage,brand_Acura,brand_Alfa,brand_Aston,brand_Audi,brand_BMW,brand_Bentley,brand_Bugatti,brand_Buick,brand_Cadillac,...,accident_None reported,fuel_type_Diesel,fuel_type_E85 Flex Fuel,fuel_type_Gasoline,fuel_type_Hybrid,fuel_type_Plug-In Hybrid,fuel_type_not supported,fuel_type_–,price,linear_predictions
0,0.031759,0,0,0,0,0,0,0,0,0,...,1,0,0,1,0,0,0,0,11000,37536.0
1,0.143728,0,0,0,0,1,0,0,0,0,...,1,0,0,1,0,0,0,0,8250,26488.0
2,0.371412,0,0,0,0,0,0,0,0,0,...,1,0,0,1,0,0,0,0,15000,26056.0
3,-1.393115,0,0,0,0,1,0,0,0,0,...,1,0,0,0,1,0,0,0,63500,68096.0
4,0.757966,0,0,0,0,0,0,0,0,0,...,1,0,0,1,0,0,0,0,7850,9576.0

In [416]:
from sklearn.metrics import root_mean_squared_error
rmse = root_mean_squared_error(df_train_sub['price'], df_train_sub['linear_predictions'])
rmse

68476.88902592132

## Polynomial Regression

In [417]:
from sklearn.preprocessing import PolynomialFeatures
poly = PolynomialFeatures(degree=2, interaction_only=True, include_bias=False)

In [418]:
X_poly = poly.fit_transform(X_train)

In [419]:
reg = LinearRegression()

In [420]:
reg.fit(X_poly, y_train)

LinearRegression()

In [421]:
reg.intercept_

1.554087129161905e+16

In [422]:
reg.coef_

array([ 1.98845574e+16,  3.08925564e+16, -4.70986952e+14, ...,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00])

In [423]:
df_train_sub['polynomial_prediction'] = reg.predict(X_poly)

In [424]:
df_train_sub.tail()

,milage,brand_Acura,brand_Alfa,brand_Aston,brand_Audi,brand_BMW,brand_Bentley,brand_Bugatti,brand_Buick,brand_Cadillac,...,fuel_type_Diesel,fuel_type_E85 Flex Fuel,fuel_type_Gasoline,fuel_type_Hybrid,fuel_type_Plug-In Hybrid,fuel_type_not supported,fuel_type_–,price,linear_predictions,polynomial_prediction
54268,-0.866793,0,0,0,0,1,0,0,0,0,...,0,0,1,0,0,0,0,29000,46040.0,49898.0
54269,0.433688,0,0,0,1,0,0,0,0,0,...,0,1,0,0,0,0,0,6500,24760.0,12602.0
54270,-0.629241,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,18950,50584.0,41242.0
54271,-1.411325,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,194965,110904.0,130658.0
54272,-0.747908,0,0,0,1,0,0,0,0,0,...,0,0,0,1,0,0,0,37499,58800.0,63514.0

In [425]:
from sklearn.metrics import root_mean_squared_error
rmse = root_mean_squared_error(df_train_sub['price'], df_train_sub['polynomial_prediction'])
rmse

67054.05607599774

In [426]:
df_test_sub = df_test.copy()

In [427]:
df_test_sub.head()

,id,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title
0,54273,Mercedes-Benz,E-Class E 350,2014,73000,Gasoline,302.0HP 3.5L V6 Cylinder Engine Gasoline Fuel,A/T,White,Beige,None reported,Yes
1,54274,Lexus,RX 350 Base,2015,128032,Gasoline,275.0HP 3.5L V6 Cylinder Engine Gasoline Fuel,8-Speed A/T,Silver,Black,None reported,Yes
2,54275,Mercedes-Benz,C-Class C 300,2015,51983,Gasoline,241.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,7-Speed A/T,Blue,White,None reported,Yes
3,54276,Land,Rover Range Rover 5.0L Supercharged Autobiogra...,2018,29500,Gasoline,518.0HP 5.0L 8 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,White,White,At least 1 accident or damage reported,Yes
4,54277,BMW,X6 xDrive40i,2020,90000,Gasoline,335.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,8-Speed A/T,White,Black,At least 1 accident or damage reported,Yes

In [428]:
df_test_sub.isnull().sum()

id              0
brand           0
model           0
model_year      0
milage          0
fuel_type       0
engine          0
transmission    0
ext_col         0
int_col         0
accident        0
clean_title     0
dtype: int64

In [429]:
df_test_sub.columns

Index(['id', 'brand', 'model', 'model_year', 'milage', 'fuel_type', 'engine',
       'transmission', 'ext_col', 'int_col', 'accident', 'clean_title'],
      dtype='object')

In [430]:
#from sklearn.preprocessing import LabelEncoder
#df_test_sub['brand_encoded'] = label_encoder.fit_transform(df_test_sub['brand'])
#df_test_sub['model_year_encoded'] = label_encoder.fit_transform(df_test_sub['model_year'])
#df_test_sub['accident_encoded'] = label_encoder.fit_transform(df_test_sub['accident'])
#df_test_sub['fuel_type_encoded'] = label_encoder.fit_transform(df_test_sub['fuel_type'])

In [431]:
df_test_sub = pd.get_dummies(df_test_sub, columns=['brand','model_year','accident','fuel_type'], dtype= np.uint8)

In [432]:
df_test_sub.head()

,id,model,milage,engine,transmission,ext_col,int_col,clean_title,brand_Acura,brand_Alfa,...,model_year_2024,accident_At least 1 accident or damage reported,accident_None reported,fuel_type_Diesel,fuel_type_E85 Flex Fuel,fuel_type_Gasoline,fuel_type_Hybrid,fuel_type_Plug-In Hybrid,fuel_type_not supported,fuel_type_–
0,54273,E-Class E 350,73000,302.0HP 3.5L V6 Cylinder Engine Gasoline Fuel,A/T,White,Beige,Yes,0,0,...,0,0,1,0,0,1,0,0,0,0
1,54274,RX 350 Base,128032,275.0HP 3.5L V6 Cylinder Engine Gasoline Fuel,8-Speed A/T,Silver,Black,Yes,0,0,...,0,0,1,0,0,1,0,0,0,0
2,54275,C-Class C 300,51983,241.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,7-Speed A/T,Blue,White,Yes,0,0,...,0,0,1,0,0,1,0,0,0,0
3,54276,Rover Range Rover 5.0L Supercharged Autobiogra...,29500,518.0HP 5.0L 8 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,White,White,Yes,0,0,...,0,1,0,0,0,1,0,0,0,0
4,54277,X6 xDrive40i,90000,335.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,8-Speed A/T,White,Black,Yes,0,0,...,0,1,0,0,0,1,0,0,0,0

In [433]:
from sklearn.preprocessing import StandardScaler
column_to_scale = 'milage'

# Initialize the StandardScaler
scaler = StandardScaler()

# Fit and transform the selected column
df_test_sub[column_to_scale] = scaler.fit_transform(df_test_sub[[column_to_scale]])

In [434]:
df_test_sub.head()

,id,model,milage,engine,transmission,ext_col,int_col,clean_title,brand_Acura,brand_Alfa,...,model_year_2024,accident_At least 1 accident or damage reported,accident_None reported,fuel_type_Diesel,fuel_type_E85 Flex Fuel,fuel_type_Gasoline,fuel_type_Hybrid,fuel_type_Plug-In Hybrid,fuel_type_not supported,fuel_type_–
0,54273,E-Class E 350,0.010268,302.0HP 3.5L V6 Cylinder Engine Gasoline Fuel,A/T,White,Beige,Yes,0,0,...,0,0,1,0,0,1,0,0,0,0
1,54274,RX 350 Base,1.095406,275.0HP 3.5L V6 Cylinder Engine Gasoline Fuel,8-Speed A/T,Silver,Black,Yes,0,0,...,0,0,1,0,0,1,0,0,0,0
2,54275,C-Class C 300,-0.404152,241.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,7-Speed A/T,Blue,White,Yes,0,0,...,0,0,1,0,0,1,0,0,0,0
3,54276,Rover Range Rover 5.0L Supercharged Autobiogra...,-0.847479,518.0HP 5.0L 8 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,White,White,Yes,0,0,...,0,1,0,0,0,1,0,0,0,0
4,54277,X6 xDrive40i,0.345479,335.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,8-Speed A/T,White,Black,Yes,0,0,...,0,1,0,0,0,1,0,0,0,0

In [445]:
#df_test_sub = df_test_sub.drop(columns = ['model', 'engine','transmission', 'ext_col', 'int_col', 'clean_title'], axis=1)
df_test_sub.shape

(36183, 98)

In [448]:
X_test = df_test_sub.to_numpy()[:,1:]
X_test

array([[ 0.01026798,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 1.0954064 ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [-0.40415188,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [ 0.85815561,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [-0.66015479,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 1.77961228,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ]])

In [449]:
X_test_poly = poly.fit_transform(X_test)

In [450]:
#df_test_sub['price'] = model.predict(X_test)

In [451]:
df_test_sub['price'] = reg.predict(X_test_poly)

In [452]:
df_test_sub.head()

,id,milage,brand_Acura,brand_Alfa,brand_Aston,brand_Audi,brand_BMW,brand_Bentley,brand_Bugatti,brand_Buick,...,accident_At least 1 accident or damage reported,accident_None reported,fuel_type_Diesel,fuel_type_E85 Flex Fuel,fuel_type_Gasoline,fuel_type_Hybrid,fuel_type_Plug-In Hybrid,fuel_type_not supported,fuel_type_–,price
0,54273,0.010268,0,0,0,0,0,0,0,0,...,0,1,0,0,1,0,0,0,0,2.112340e+05
1,54274,1.095406,0,0,0,0,0,0,0,0,...,0,1,0,0,1,0,0,0,0,1.967400e+04
2,54275,-0.404152,0,0,0,0,0,0,0,0,...,0,1,0,0,1,0,0,0,0,-1.745606e+15
3,54276,-0.847479,0,0,0,0,0,0,0,0,...,1,0,0,0,1,0,0,0,0,4.367400e+04
4,54277,0.345479,0,0,0,0,1,0,0,0,...,1,0,0,0,1,0,0,0,0,4.647400e+04

In [ ]:
#df_test_sub[['id','price']].to_csv('submission_linear_regression.csv',index=False)

In [453]:
df_test_sub[['id','price']].to_csv('submission_polynomial_regression.csv',index=False)